apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: prod
on:
  workflow_dispatch:

jobs:
  deploy:
    steps:
      - uses: cloudbees-io/register-deployed-artifact@v2
        with:
          labels: aspm-test
          artifact-id: f6a25a87-b31e-4393-bedc-ae76524a99e0
          target-environment: ecr-qa